GOOGLE_API_KEY = "AIzaSyAHG5Ja4duoxx2aIsDYmD28Jh7CoMHShpY"
TAVILY_API_KEY = "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"
COHERE_API_KEY = "hys8F69llN5PPXpRjxH1qdZh2jYeEkymSqoBtoMM"
ZENDESK_SUBDOMAIN = "omarilabs"
ZENDESK_API_KEY = "OngXFxYwet6eRjlvIZfYE79g4cheFvOmXyfBP2Rf"
ZENDESK_EMAIL = "dev.omari.ai@gmail.com"
PINECONE_API_KEY="pcsk_6uE7M2_G5MpX6wUNPKZZLQKtKxXyjSTdVsfqZpVw1tu5JK8ahFTnSsiPEPw15mJFiWD98x"
PINECONE_INDEX_NAME="faq"
GROQ_API_KEY="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"